openapi: 3.0.0
info:
  description: get customers details by customerId
  version: "1.0.0"
  title: ng-Customers API
  contact:
    email: abhikmyadav1310@gmail.com
  license:
    name: Apache 2.0
    url: 'http://localhost:3000'
tags:
  - name: Customers
    description: Operations related to customer details
paths:
  /customers/{customerId}:
    get:
      tags:
        - customers
      summary: Retrieve customer details
      description: |
        Get customer information based on  customer ID.
      parameters:
        - in: path
          name: customerId
          description: customerId as a path parameter.
          required: true
          schema:
            type: string
       
      responses:
        '200':
          description: Customer details retrieved successfully.
          content:
            application/jsonApi:
              schema:
                type: object
                properties:
                  customerId:
                    type: string
                    example: "3678905"
                  appliances:
                    type: object
                    properties:
                      age:
                        type: string
                        example: "12"
                      applianceId:
                        type: string
                        example: "26543260"
                      applianceName:
                        type: string
                        example: "Gas Cooker"
                      category:
                        type: string
                        example : "gas" 
                      manufactureDate:
                        type: string
                        example: ""
                  email:
                    type: string
                    example: "stevejobs@gmail.com"
                  firstName:
                    type: string
                    example: "Steve"
                  lastName:
                    type: string
                    example: "Jobs"
                  phonenumber:
                    type: string
                    example: "9080706050"
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          description: Invalid request
          content:
            application/jsonApi:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid email ID
                  status:
                    type: integer
                    example: 400
                items:
                  $ref: '#/components/schemas/InvalidRequest'
                    
        '401':
          description: Unauthorized
          content:
            application/jsonApi:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized access
                  status:
                    type: integer
                    example: 401
                items:
                  $ref: '#/components/schemas/UnauthorizedError'

        '500':
          description: Internal Server Error
          content:
            application/jsonApi:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Internal server error
                  status:
                    type: integer
                    example: 500
                items:
                  $ref: '#/components/schemas/InternalServerError'

components:
  schemas:

    Customer:
      type: object
      properties:
        customerId:
          type: string
          example: "3678905"
        appliances:
          type: object
          properties:
            age:
              type: string
              example: "12"
            applianceId:
              type: string
              example: "26543260"
            applianceName:
              type: string
              example: "Gas Cooker"
            category:
              type: string
              example: "gas"
            manufactureDate:
              type: string
              example: "2012-11-17"
        email:
          type: string
          example: "stevejobs@gmail.com"
        firstName:
          type: string
          example: "Steve"
        lastName:
          type: string
          example: "Jobs"
        phonenumber:
          type: string
          example: "9080706050"
          
    InvalidRequest:
      type: object
      properties:
        error:
          type: string
          example: Invalid email ID
        status:
          type: integer
          example: 400
                  
             

    UnauthorizedError:
      type: object
      properties:
        error:
          type: string
          example: Unauthorized access
        status:
          type: integer
          example: 401
                  
                  
                  
    InternalServerError:
      type: object
      properties:
        error:
          type: string
          example: Internal server error
        status:
          type: integer
          example: 500

         
    
servers:
  # Added by API Auto Mocking Plugin
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ABHIKMYADAV131001/ng-customers/1.0.0
  - description: SwaggerHub API Auto Mocking
    url: https://localhost:3000