---
openapi: 3.0.0
info:
  title: ng-Customers API
  description: get customers details by customerId
  contact:
    email: abhikmyadav1310@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/ABHIKMYADAV131001/ng-customers/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: Customers
  description: Operations related to customer details
- name: customers
  description: Operations related to customer details
paths:
  /customers:
    get:
      tags:
      - customers
      summary: Retrieve customer details
      description: |
        Get customer information based on  customer ID.
      operationId: searchInventory
      parameters:
      - name: customerId
        in: query
        description: Account number of the customer.
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: OK. Customer details retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                properties:
                  email:
                    type: string
                    example: abhishek@gmail.com
                  accountNumber:
                    type: array
                    items:
                      type: integer
                  customerId:
                    type: integer
                    example: 3678905
                  password:
                    type: string
                    format: password
                    example: axfa_1g2g2vgavava
                items:
                  $ref: '#/components/schemas/Customer'
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_401'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
components:
  schemas:
    Customer:
      type: object
      properties:
        email:
          type: string
          example: abhishek@gmail.com
        accountNumber:
          type: array
          items:
            type: integer
        customerId:
          type: integer
          example: 3678905
        password:
          type: string
          format: password
          example: axfa_1g2g2vgavava
    inline_response_400:
      type: object
      properties:
        error:
          type: string
          example: Invalid email ID
    inline_response_401:
      type: object
      properties:
        error:
          type: string
          example: Unauthorized access
    inline_response_500:
      type: object
      properties:
        error:
          type: string
          example: Internal server error
